name: Deploy Front

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t frontend_image .

      - name: Save image
        run: |
          docker save frontend_image -o frontend.tar

      - name: Fix Permissions
        run: |
          chmod +r frontend.tar

      - name: Zip image
        run: |
          gzip frontend.tar
          ls

      - name: Transfer Source Code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVERR_PASSPHRASE }}
          source: .
          target: ~/

      - name: List files after transfer
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "ls -al ~"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVERR_PASSPHRASE }}
          script: |
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker rmi frontend_image || true
            docker load -i frontend.tar.gz
            docker ps -a  # Verifica se o contêiner foi criado
            docker run --name frontend-container -d -p 80:3000 frontend_image  # Assumindo que o Next.js está na porta 3000
            docker logs frontend-container  # Verifica os logs do contêiner
