name: Deploy Front

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t frontend_image .
      - name: Save image
        run: |
          docker save frontend_image -o frontend.tar

      - name: Fix Permissions
        run: |
          chmod +r frontend.tar

      - name: Zip image
        run: |
          gzip frontend.tar
          ls

      - name: Transfer Source Code
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: $ {{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVERR_PASSPHRASE }}
          source: .
          target: ~/

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVERR_PASSPHRASE }}
          script: |
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker rmi frontend_image || true
            docker load -i frontend.tar.gz 
            docker run --name frontend-container -d -p 80:80 frontend_image
            cd ~
